language: clojure
lein:     lein2
script:   "lein2 with-profile +$CLOJURE_VERSION midje"
before_install:
  - sudo add-apt-repository -y ppa:wnoronha/thrift
  - sudo apt-get update -qq
  - sudo apt-get install -qq thrift-compiler
  - which thrift
branches:
  only:
    - master
jdk:
  - openjdk6
  - openjdk7
  - oraclejdk7
env:
  - CLOJURE_VERSION=1.3
  - CLOJURE_VERSION=1.4
  - CLOJURE_VERSION=1.5
  - CLOJURE_VERSION=1.6
matrix:
  allow_failures:
    - env: CLOJURE_VERSION=1.6
